name: Test README blog posts

on:
  pull_request:

permissions:
  contents: read

jobs:
  test-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install --frozen-lockfile

      - name: Update README
        run: bun run update-readme

      - name: Lint code
        run: bun run lint

      - name: Diff?
        run: git diff
